stages:
  - dummy
  - dev
  - test
  - deploy

Ready Step:
  stage: dummy
  script:
    - echo "Ready"
  tags:
    - SMFE
  only:
    - /^tag__.+__.+/

dev:
  stage: dev
  script:
    - echo $GITLAB_USER_EMAIL $USER $CI_PROJECT_URL $CI_COMMIT_REF_NAME $CI_PROJECT_NAME $CI_COMMIT_REF_SLUG
    - cnpm install @mfelibs/ci-runner-script
    - node ./node_modules/@mfelibs/ci-runner-script/index.js $GITLAB_USER_EMAIL $USER $CI_PROJECT_URL $CI_COMMIT_REF_NAME $CI_PROJECT_NAME dev excute
  tags:
    - SMFE
  when: manual
  only:
    - /^tag__.+__.+/

simulate:
  stage: test
  script:
    - echo $GITLAB_USER_EMAIL $USER $CI_PROJECT_URL $CI_COMMIT_REF_NAME $CI_PROJECT_NAME $CI_COMMIT_REF_SLUG
    - cnpm install @mfelibs/ci-runner-script
    - node ./node_modules/@mfelibs/ci-runner-script/index.js $GITLAB_USER_EMAIL $USER $CI_PROJECT_URL $CI_COMMIT_REF_NAME $CI_PROJECT_NAME simulate excute
  tags:
    - SMFE
  when: manual
  only:
    - /^tag__.+__.+/

deploy:
  stage: deploy
  script:
    - echo $GITLAB_USER_EMAIL $USER $CI_PROJECT_URL $CI_COMMIT_REF_NAME $CI_PROJECT_NAME $CI_COMMIT_REF_SLUG
    - cnpm install @mfelibs/ci-runner-script
    - node ./node_modules/@mfelibs/ci-runner-script/index.js $GITLAB_USER_EMAIL $USER $CI_PROJECT_URL $CI_COMMIT_REF_NAME $CI_PROJECT_NAME nogrey excute
  tags:
    - SMFE
  when: manual
  only:
    - /^tag__.+__.+/

grey:
  stage: deploy
  script:
    - echo $GITLAB_USER_EMAIL $USER $CI_PROJECT_URL $CI_COMMIT_REF_NAME $CI_PROJECT_NAME $CI_COMMIT_REF_SLUG
    - cnpm install @mfelibs/ci-runner-script
    - node ./node_modules/@mfelibs/ci-runner-script/index.js $GITLAB_USER_EMAIL $USER $CI_PROJECT_URL $CI_COMMIT_REF_NAME $CI_PROJECT_NAME grey excute
  tags:
    - SMFE
  when: manual
  only:
    - /^tag__.+__.+/
